name: Staging Rebuild all Docker images

on: push

jobs:
  build_dockerfiles:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app_name: [video_converter, not_exist]
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      working-directory: ${{ matrix.app_name }}
      run: docker build . --file Dockerfile --tag psp_${{ matrix.app_name }}:$(date +%s)
