name: Build and publish projects images

on: push

jobs:
  build_dockerfiles:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app_name: [video_converter]
    steps:
    - uses: actions/checkout@v4
    - name: Set short git commit SHA
      id: vars
      run: |
       calculatedSha=$(git rev-parse --short ${{ github.sha }})
       echo "COMMIT_SHORT_SHA=$calculatedSha"
       echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
    # - name: Build the Docker image
    #   continue-on-error: true
    #   working-directory: ${{ matrix.app_name }}
    #   run: docker build . --file Dockerfile --tag psp_${{ matrix.app_name }}:$(date +%s)
    - name: Build and publish a Docker image for ${{ github.repository }}
      uses: macbre/push-to-ghcr@master
      with:
        working-directory: ${{ matrix.app_name }}
        image_name: ${{ github.repository }}_videoconverter  # it will be lowercased internally
        image_tag: ${{ env.COMMIT_SHORT_SHA }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
