name: Staging build and publish projects images

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app_name: [video_converter]
    permissions:
      contents: read
      packages: write
    steps:
    # - uses: actions/checkout@v4
    - name: Extract branch name
      id: vars
      run: echo "BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
    # - name: Build and publish a Docker image for ${{ github.repository }}
    #   uses: macbre/push-to-ghcr@master
    #   with:
    #     dockerfile: ${{ matrix.app_name }}/Dockerfile
    #     image_name: ${{ github.repository }}_${{ matrix.app_name }}  # it will be lowercased internally
    #     image_tag: ${{ env.BRANCH }}
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build dockerfile for ${{ matrix.app_name }}
      uses: docker/build-push-action@v6
      with:
        file:: ${{ matrix.app_name }}/Dockerfile
        push: false
        tags: ${{ github.repository }}_${{ matrix.app_name }}:${{ env.BRANCH }}
        outputs: type=docker,dest=${{ runner.temp }}/${{ github.repository }}_${{ matrix.app_name }}.tar 
    - name: Upload docker image for ${{ matrix.app_name }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.repository }}_${{ matrix.app_name }}
        path: ${{ runner.temp }}/${{ github.repository }}_${{ matrix.app_name }}.tar

  scan:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        app_name: [video_converter]
    permissions:
      contents: read
      packages: write
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ github.repository }}_${{ matrix.app_name }}
        path: ${{ runner.temp }}

    - name: Load image
      run: |
        docker load --input ${{ runner.temp }}/${{ github.repository }}_${{ matrix.app_name }}.tar
        docker image ls -a
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@latest
      with:
        image-ref: '${{ github.repository }}_${{ matrix.app_name }}:${{ env.BRANCH }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
