name: Staging build and publish projects images

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app_name: [video_converter]
    steps:
    - uses: actions/checkout@v4
    - name: Extract branch name
      id: vars
      run: echo "BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build dockerfile for ${{ matrix.app_name }}
      uses: docker/build-push-action@v6
      with:
        file: ${{ matrix.app_name }}/Dockerfile
        push: false
        tags: ${{ github.repository }}_${{ matrix.app_name }}:${{ env.BRANCH }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        load: true
        outputs: type=docker,dest=${{ runner.temp }}/${{ matrix.app_name }}.tar
    - name: Upload docker image for ${{ matrix.app_name }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.app_name }}
        path: ${{ runner.temp }}/${{ matrix.app_name }}.tar

  scan:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        app_name: [video_converter]
    permissions:
      contents: read
      packages: write
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.app_name }}
        path: ${{ runner.temp }}
    - name: Extract branch name
      id: vars
      run: echo "BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
    - name: Load image
      run: |
        docker load --input ${{ runner.temp }}/${{ matrix.app_name }}.tar
        docker image ls -a
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.31.0
      with:
        image-ref: '${{ github.repository }}_${{ matrix.app_name }}:${{ env.BRANCH }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
