name: Staging build and publish projects images

on: push

jobs:
  build_dockerfiles:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app_name: [video_converter]
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Extract branch name
      id: vars
      run: echo "BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
    - name: Build and publish a Docker image for ${{ github.repository }}
      uses: macbre/push-to-ghcr@master
      with:
        dockerfile: ${{ matrix.app_name }}/Dockerfile
        image_name: ${{ github.repository }}_videoconverter  # it will be lowercased internally
        image_tag: ${{ env.BRANCH }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
